name: AI Facts Auto Post

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install FFmpeg and Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-dejavu-core fonts-freefont-ttf

      - name: Verify FFmpeg
        run: |
          which ffmpeg
          ffmpeg -version

      - name: Install Dependencies
        run: npm install

      - name: Create YouTube Credential Files
        run: |
          echo '${{ secrets.YT_CLIENT_SECRET }}' > client_secret.json
          echo '${{ secrets.YT_TOKEN }}' > token.json

      - name: Generate Video + Upload Facebook
        run: node main.js
        env:
          PAGE_ID: ${{ secrets.PAGE_ID }}
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Upload To YouTube
        run: node youtube-upload.js