name: Facebook Upload

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node upload-facebook.js
        env:
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}